# Generated by Django 5.1.1 on 2024-09-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payme", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchanttransactionsmodel",
            options={
                "verbose_name": "Merchant Transaction",
                "verbose_name_plural": "Merchant Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "managed": False,
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="amount",
            field=models.FloatField(blank=True, null=True, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="cancel_time",
            field=models.BigIntegerField(
                default=0, null=True, verbose_name="Cancel Time"
            ),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="created_at_ms",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Created At MS"
            ),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="order_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Order ID"
            ),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="perform_time",
            field=models.BigIntegerField(
                default=0, null=True, verbose_name="Perform Time"
            ),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reason"
            ),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="state",
            field=models.IntegerField(default=1, null=True, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="time",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="transaction_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Transaction ID"
            ),
        ),
        migrations.AlterField(
            model_name="merchanttransactionsmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
