name: Documentation

on:
  push:
    branches:
      - payme-pkg-3.0b
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements/docs-requirements.txt
      - run: mkdocs gh-deploy --force
